### ISSUE TITLE
Android automagic sync doesn't sometimes.

### ISSUE THREAD

**Issue by sshaikh** [Automattic/simplenote-android#1052] opened 2020-06-01 11:41 UTC
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to report a bug, may be closed without action.

### Expected
Various platforms to sync in a timely manner.

### Observed
out of order versions as a result of unreliable sync.

### Reproduced

The following steps may reproduce. Note that they are not done with any kind of speed, so I don't think this is a timing issue.

1) add 10 lines via electron, verify up to date note on Android (v1)
2) add lines on android. press power button on phone, switch out (etc), v2
3) delete different lines on electron, v3
4) open android app. still see v2. this then gets pushed as the latest version, v4.
5) see v4 (ie v2) on electron. history shows all versions including the clobbered v3.
6) restoring v3 puts everything back.

I've had various issues like these with Simplenote up to the point where I am now anxious to touch any notes on a different device until I've done a visual inspection that the note has transferred okay.

As many others have said, this seems to be easily solvable with a "sync now" button or even a "last saved" timestamp, as at least then you can stop what you're doing until a resolution is found. These dates seem to be available in the history browser where they do come in useful when fixing these kind of mixups.

Unfortunately silent automatic magical syncs just doesn't work on the edges, and is painful when it goes wrong.

**Comment by theck13** [comment] 2020-06-01 13:10
Thanks for the report!

The behavior you're describing appears to be a duplicate of https://github.com/Automattic/simplenote-android/issues/992, which is included in Simplenote Android 2.6.0 scheduled for release June 1st.  The "sync now " button is a duplicate of https://github.com/Automattic/simplenote-android/issues/945.  As described in a link in that issue, a manual sync button isn't possible for a few reason.

- If automatic sync doesn't work, manual sync won't work.
- Syncing sends changes _*immediately*_ to the backend when a network connection is available.
- When no network is available, changes are stored locally.
- Once a network connection is reestablished, changes are synced.
- There is no timer that dictates when syncing occurs, and literally no entry point in which a sync event could be forced.

Since these are duplicates, I'm closing this issue.

**Closed by theck13** 2020-06-01 13:10 UTC
Labels: bug

**Comment by sshaikh** [comment] 2020-06-01 13:42
Thank you for the update. I think it's important to note that I didn't lose changes in this instant (although it could be the same root cause manifesting differently).

Thank you for the references too - I've moved my thoughts there (even though those are also closed)
