### ISSUE TITLE
Weird behavior with checkboxes

### ISSUE THREAD

**Issue by maxme** [Automattic/simplenote-android#983] opened 2020-03-10 13:57 UTC
### Expected
Checkbox appears when I tap the "check list" button.

### Observed
A blue underline (spell checker?) is shown instead of a checkbox.

![Screenshot_20200310_144047_com automattic simplenote](https://user-images.githubusercontent.com/40213/76319154-1521ff00-62df-11ea-9381-13cafc9a1121.jpg)

Demo video: https://bia.is/s/BvWY/SVID_20200310_144253_1.mp4

I first thought this was related to markdown mode, but I can repro without markdown.

### Reproduced

1. Create a new note
2. Tap the "check list" button
3. Notice the blue underline.

Make|Model|Android Version|App Version
-|-|-|-
Huawei|P30|Andorid 9|2.5-rc-1

**Comment by theck13** [comment] 2020-03-10 14:00
This is a duplicate of https://github.com/Automattic/simplenote-android/issues/980.  It was fixed in https://github.com/Automattic/simplenote-android/pull/981.

**Closed by theck13** 2020-03-10 14:00 UTC
Labels: bug
