### ISSUE TITLE
Keyboard doesn't automatically appear when creating a new note

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-android#439] opened 2017-03-15 09:28 UTC
A user reports that when they first open the app and create a new note after it has been closed or the device restarted the keyboard does not appear automatically. When the user taps to open the keyboard, types some text, then returns to the list of notes the text they typed disappears. I can't reproduce this on my Samsung phone or tablet. It's happening for the user on a Samsung Galaxy Note II. The user is using the Swift keyboard but says it happens with the stock Samsung keyboard also.  

**Steps to reproduce:**

1. Reload the phone or remove the app from running applications.
2. Start the app.
3. Tap "New note" button. It goes to the new note screen. But it doesn't
open keyboard automatically.
4. Tap the textbox. Keyboard opens. Write some text and tags.
5. Tap back button on the screen or on the device.
6. New note without any text is added. It completely forgets the text and
tags.

#3108922-t

**Comment by theck13** [comment] 2019-05-23 17:18
I cannot reproduce that behavior, but this appears to be fixed in https://github.com/Automattic/simplenote-android/issues/351.  Feel free to reopen this issue if you can.

**Closed by theck13** 2019-05-23 17:18 UTC
Labels: bug
