### ISSUE TITLE
Tag list order

### ISSUE THREAD

**Issue by memeplex** [Automattic/simplenote-android#428] opened 2017-02-15 14:36 UTC
There are some open issuses for nested tags and folders, but there are many workarounds for that using a well designed naming convention to sort tags in a hierarchical or another fashion.

The 80/20 would suggest you sort the tags in the sidebar in alphabetical order! Currently they're displayed in creation time order, which is mostly random and useless.

**Comment by gracie** [comment] 2017-06-12 14:19
Another request in #3241529-t, asking to be able to reorder tags within the Android app, according to individual preference.

**Comment by GeoJunkie** [comment] 2017-09-25 18:17
Another request in #696030-zen for user to be able to reorder tags in Android.

**Comment by roundhill** [comment] 2018-03-21 17:47
Dupe of #283

**Closed by roundhill** 2018-03-21 17:47 UTC
Labels: duplicate, enhancement
