### ISSUE TITLE
Sync Status/Last Sync'd Indicator

### ISSUE THREAD

**Issue by sshaikh** [Automattic/simplenote-android#1181] opened 2020-10-19 15:57 UTC
### What
I understand that this has been asked before, but I don't think the issue has been discussed enough, especially in the presence of ongoing sync issues (eg #992). However in light of the following, which suggests a deliberate design decision, I feel that there's more of a case to have such a label.

I've experienced sync issues of some kind since I've started using Simplenote. However what's interesting is that these seem to be getting worse, although that could just be noticing issues as I increasingly grow to depend on it more. Recently I was asked to repeat these symptoms to support who gave me the following explanation:

> Simplenote Android does not sync in the background by design in order to minimize the amount of data used without your knowledge. In other words, the app only syncs when it is open. Syncing is dependent upon the size of changes and the network speed. If there is little or no network connection, the app will store the changes until a network connection is established and the app is open. If there was as issue with the changes or network speed, that is why you had to reopen the app to get the changes from your Android device to sync.

I actually think that this is fair enough and a good basis on which to design a sync workflow.

The issue however is that the user doesn't know that they are experiencing sync issues until (at least in my case) they try to view the note elsewhere (eg via the Electron app on Windows). After a brief period of dissonance and self doubt ("I'm sure I updated this yesterday?"), the solution seems to be to find your android device, open the app, confirm your doubt with a visual diff and then keep the app open until the Electron view updates and you know that the otherwise transparent action on the Android app has been successful.

### Why
Ultimately the problem is that there is no objective way to determine the sync status of a note without doing a visual diff between two applications on the same note. In the absence of that visual diff (I'd like not to have to do that every time I edit a note), you have to rely on memory.  Memory and visual diffs are both error prone and for me the reason I'd like to use a reliable note taking app in the first place!

To be clear it's not the non-syncing that's frustrating here, it's the not knowing that it didn't happen until some time after when your head is in a different context that is irritating at best and dangerous (if you lose an update) at worst.

### How
With some kind of date label (or "last updated x seconds ago" like Google Docs would use), the user would know that a note hasn't yet been synchronised, and so know to keep the app open, refrain from trying another application until it is or even mitigate it some other way by copying it over or checking their internet connection.

In the rare times that Google Docs says that it is having trouble saving, I know not to quit my browser (and if not resolved quick enough I can take more drastic measures like saving my work elsewhere, although I've never had to rely on that copy as I'm told by GD when the save eventually happens. Similarly with such a label in Simplenote I would know not to exit the app (or fix my network).

It seems this should be possible as the app knows when there are network problems:

> If there is little or no network connection, the app will store the changes until a network connection is established and the app is open. 

I notice that this has been considered by the electron app here https://github.com/Automattic/simplenote-electron/issues/2162, although I've yet to see it in the UI. I hope that means that there isn't a fundamental aversion to such a feature.

**Comment by theck13** [comment] 2020-10-19 17:22
There are multiple approaches we are still considering (e.g. https://github.com/Automattic/simplenote-android/pull/1137, https://github.com/Automattic/simplenote-android/pull/1140, https://github.com/Simperium/simperium-android/pull/226).  The closest thing to your suggestion would be https://github.com/Automattic/simplenote-android/pull/1140, which has a **_Synced_** date/time at the top of the **_Information_** sheet.  We don't have a definitive solution yet, but we're still working on it.

As you mentioned, this is a duplicate of #945.  I'm closing this issue as such.

**Closed as completed by theck13** 2020-10-19 17:22 UTC
Labels: duplicate

**Comment by sshaikh** [comment] 2020-10-19 17:34
Thanks for the pointers. I've subscribed to those - hopefully something will shake out of this.

I'd say that asking for a sync button isn't a dupe, but a lot of the same issues are dealt with in #945 . It's interesting how the same conversation keeps being had (usually by me - just goes to show how bad my memory is!)
