### ISSUE TITLE
Peril warning for non-translatable strings are not firing

### ISSUE THREAD

**Issue by danilo04** [Automattic/simplenote-android#1435] opened 2021-08-05 22:17 UTC
In the PR #1387 was discussed that some of the Peril warnings were not firing when adding attributes to a reference string in `string.xml`

**Comment by AliSoftware** [comment] 2021-08-10 13:19
@danilo04 If you feel adventurous into installing the tooling (npm, yarn, …), one way of testing this would be to add more [unit tests](https://github.com/Automattic/peril-settings/blob/master/tests/android-test.ts) to our [Peril rules](https://github.com/Automattic/peril-settings/blob/master/org/pr/android.ts) to check why it doesn't trigger. Then use `yarn test` to run the new tests.

Hopefully, adding more examples in our unit tests will make them go red, allowing you to reproduce the issue and find the reason for failure on Peril to fire on those, and thus fix the issue. (If even adding more unit tests to the Peril rule doesn't make them go red, that means the reason is elsewhere but harder to find if not easy to reproduce… but at least it's worth trying that option first)

If the first approach doesn't work, another thing worth trying could be to introduce those reference strings in another Android repo (e.g. WPAndroid or WCAndroid) in a draft PR and see if you get the Peril warning there. If you get it on WPAndroid but not here on SNAndroid, that will give you a clue to look at the potential differences between those repos (even though [`simplenote-android` seems to be properly configured in `peril-settings.json` to run that rule](https://github.com/Automattic/peril-settings/blob/master/peril-settings.json#L100-L102) like all other Android repos…)

**Comment by danilo04** [comment] 2021-08-10 14:30
Thanks for the pointers @AliSoftware. I think that is the best way to spot the problem since it would be harder to debug directly on the repo.

**Comment by danilo04** [comment] 2021-08-31 13:00
HI @AliSoftware 👋 ,

I tested on Wordpres-Android (https://github.com/wordpress-mobile/WordPress-Android/pull/15260) and the check for strings is working correctly:

![](https://d.pr/i/yCOtUY+.jpg)

As I mentioned in the chat too, I have tested adding an issue and a PR with and without labels and those checks work correctly.

**Comment by danilo04** [comment] 2021-08-31 19:07
Now it seems to be working on https://github.com/Automattic/simplenote-android/pull/1460:

![](https://d.pr/i/VuZM46+.jpg)

**Comment by danilo04** [comment] 2021-08-31 19:21
### Summary of Events

@AliSoftware I will include a summary of the events that I think make Peril work again in `simplenote-android`. It is clear to me now that it was not working before even for labels on issues. 

1. Created this PR #1435
2. Created issue #1461 with my current account
3. Created issue #1462 with another account I used for my trial. I remembered that for all the issues I created with my trial account, Peril raised warnings if there weren't labels set. So I tried the scenario to test whether Peril work for an account that doesn't belong to the organization.
4. Saw that Peril warnings for labels were firing in #1462 but not in #1461
5. After some time, saw that Peril warnings were also firing in #1461
6. At this point I thought that was not a problem, but then I remembered that for Issues created in the last month, Peril did not raise any warnings even though they didn't have the needed labels. I observed that for the issues created after I created issue #1462, Peril was working properly. 
7. So I committed again another `translatable` string to #1435 and this time Peril warnings were fired. 

### Conclusion
Either there were some changes or deployment to Peril, or the #1462 issue that I created with my other account reactivated the Peril checks somehow. To understand a little bit what happened, I will have to check the logs, but I don't have access yet.

**Comment by AliSoftware** [comment] 2021-09-01 20:11
Thanks for the detailed summary.

Given that it appears to be working according to your summary and tests, and that Heroku doesn't have a very long retention for logs – so we won't have any error logs for the past occurrences when it wasn't working months ago for you to use to debug it further anyway – I say we could close this issue.

@mokagio do you concur?

**Comment by mokagio** [comment] 2021-09-01 23:04
+1, let's close it.

There's quite a few moving pieces involved in running Peril: GitHub APIs and web hooks, Heroku, the Peril code itself, the code we wrote for the rules... There might have been a hiccup in some of the pieces outside of our control for some time.

We shall open this again and do more research if the issue resurfaces.

**Closed as completed by mokagio** 2021-09-01 23:04 UTC
Labels: tooling
