### ISSUE TITLE
Notes open twice when chosen from All Notes screen

### ISSUE THREAD

**Issue by msilbers** [Automattic/simplenote-android#818] opened 2019-09-29 18:11 UTC
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to report a bug, may be closed without action.

### Expected
It's expected that tapping on a note to open it would open that note once.

### Observed
- As reported by a Simplenote user, tapping some notes (especially longer notes) results in it opening twice. The different versions can also overwrite each other.
- I can only replicate this when I double-tap on a note to open it, but I believe it still shouldn't open twice.

### Reproduced
1. Open Simplenote on an Android device
2. Tap on a note or double-tap on one
3. See that the note appears to open twice
4. Hitting back will go to the first open note
5. Hitting back again finally goes to the All Notes list

Make|Model|Android Version|App Version
-|-|-|-
Huawei | BND-L24 | EMUI 8.0.0.355(C567) on Android 8.0 | Simplenote 2.0
Samsung | Note 10 | Android 9.0 | Simplenote 2.0

**Comment by theck13** [comment] 2019-10-16 21:07
I'm unable to reproduce the note-opening-twice behavior by single-tapping.  I'm able to reproduce it when double-tapping notes with hundreds of lines and thousands of characters.  Therefore, this appears to be a duplicate of https://github.com/Automattic/simplenote-android/issues/661.  @msilbers, can you confirm it is the same issue?

**Comment by theck13** [comment] 2019-10-18 15:07
I'll close this issue and mark it as `duplicate` since it has the same behavior as https://github.com/Automattic/simplenote-android/issues/661.

**Closed by theck13** 2019-10-18 15:07 UTC
Labels: bug
