### ISSUE TITLE
Search is case sensitive for Cyrillic languages

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-android#278] opened 2015-03-23 17:23 UTC
Steps:
1. Create a note with the word Бабушка (Grandmother in Ukranian and Russian).
2. Search for the lower case version in the Android app - бабушка. The search doesn't return the note with the same word but an upper case first letter.

**Comment by aportbury** [comment] 2017-07-14 05:01
Another report: Ticket=#3317329

**Comment by JesseStu** [comment] 2018-04-24 13:48
This user adds another report and left a review noting the bug on the Play Store: #1100380-zen

**Comment by nagpai** [comment] 2018-05-20 09:50
another report with related issue: #1169860-zen

**Comment by SiobhyB** [comment] 2019-02-13 13:47
Reopening as we had another report of this issue here:

> The app is good, but I don’t use it, because Cyrillic search only works with case-sensitive: ((In Latin, the search works fine, case-insensitive) For developers, this problem is on the task list, but it has been hanging there for several years! When Will she fix it?

I tested and was able to reproduce by following Rachel's steps.

**Comment by theck13** [comment] 2019-05-21 01:44
I can't reproduce that behavior.  Feel free to reopen this issue if you can.  I tested on Simplenote 1.7.0 with both of Rachel's steps above.  See the animation below for illustration.

<img src="https://user-images.githubusercontent.com/3827611/58062403-84074f00-7b37-11e9-901d-0a0f486840e5.gif" width="360">

This was also [verified as fixed for Greek in the issue](https://github.com/Automattic/simplenote-android/pull/557#issuecomment-419380586).

**Comment by atestovgit** [comment] 2019-06-18 19:28
Hi! Issue is still reproduced on my Samsung Galaxy S7 with Android 8.0.0 version and Simplenote 1.7.0 version. Also I know that it is reproduced on Samsung Galaxy S9 with Android 9 version. Issue is NOT reproduced on Samsung J3 with Android 8.0.0 and HTC (don't know model) with Android 8.0.0 version. All these smartphones use Russian UI except HTC which uses English. Animation below is from Samsung Galaxy S7:
![20190618_215541](https://user-images.githubusercontent.com/51711036/59713309-cb0c6100-9217-11e9-8af4-9de998a5ec53.gif)
Please, reopen an issue...

**Comment by SiobhyB** [comment] 2019-06-19 11:21
Tested and confirmed I can replicate the issue by following the steps in Rachel's first comment (as well as the steps shown in the last animation from @atestovgit):

> 1. Create a note with the word Бабушка (Grandmother in Ukranian and Russian).
> 2. Search for the lower case version in the Android app - бабушка. The search doesn't return the note with the same word but an upper case first letter.

I tested on a Pixel with Android 9.

**Comment by gtsiolis** [comment] 2019-10-29 09:37
This seems to be resolved in the latest release. However, now you can't search for hyphenated characters without hyphenation. I've added https://github.com/Automattic/simplenote-android/issues/861 for this.

**Comment by theck13** [comment] 2019-12-17 19:04
I'm still unable to reproduce this issue.  I tested with English and Russian selected as the language with the following devices:

Make|Model|Android Version|App Version
-|-|-|-
Google|Pixel|8.0.0|2.2.0
Google|Pixel|9.0.0|2.2.0
Google|Pixel 2|7.1.0|2.2.0
Google|Pixel 3|10.0.0|2.2.0
Google|Pixel 4|10.0.0|2.2.0
Samsung|Galaxy S6|7.0.0|2.2.0
ZTE|Maven 2|7.0.0|2.2.0

If you are still seeing this issue, make sure you have updated to Simplenote 2.2.0.  If you continue to see issues after updating, email us at support@simplenoteapp.com for help.

**Comment by eduardozulian** [comment] 2021-02-25 19:43
Reopening this after a report in 3768731-zen

* Device: OnePlus 3T with Android 8
* Simplenote v.2.15(130).

There are two screenshots and further device info in the user's report.

**Comment by poojashetty18** [comment] 2021-03-09 09:04
Another report on 3802717-zen on version 2.15 (130)

**Comment by amatus-** [comment] 2021-12-21 03:18
My Samsung Galaxy s8 with Android 9 is also affected by this bug (Simplenote 2.23).

**Comment by CameronMilliken** [comment] 2022-05-04 17:41
Searching for any word in the android application gives the following as in the screenshot
![Screenshot_20220504_085910_com automattic simplenote](https://user-images.githubusercontent.com/36011531/166747442-ff6cd0f8-7af9-4c45-bf6e-284d9b92c42a.jpg)

https://woothemes.zendesk.com/agent/tickets/5188645

**Comment by amatus-** [comment] 2022-12-23 15:10
The bug is still present on my Google Pixel 6 pro.

**Closed** 2024-05-13 20:08 UTC
Labels: [Type] Bug
