### ISSUE TITLE
Notes with 144+ characters appearing blank after making edits

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/simplenote-android#625] opened 2019-01-22 22:36 UTC
#### Steps to reproduce
1. Open a note with at least 144 characters
2. Add text in the middle of the note

#### What I expected
Text would be placed in the note, editing could continue

#### What happened instead
Once the space bar is hit, the note becomes blank. Exiting out of the note and re-opening will show the note content with the edit to appear, but continued edits will result in a blank screen again

#### Simplenote version
v.1.6.7 

#### OS version
Android 6.0

#### Screenshot / Video
Available here: [https://cld.wthms.co/5TYHfR](https://cld.wthms.co/5TYHfR)

Reported in #1724492-zen

**Comment by theck13** [comment] 2019-05-29 06:52
In the linked video, some actions in the app bar are disabled suggesting the note view is changed from _Edit_ to the _Preview_ tab even though markdown is not enabled.  This may be related to https://github.com/Automattic/simplenote-android/issues/472.

**Comment by theck13** [comment] 2019-12-18 20:44
Since it can't be reproduced with any note containing more than 144 characters and the video looks like a different root cause, this does appear to be a duplicate of https://github.com/Automattic/simplenote-android/issues/472.

**Closed by theck13** 2019-12-18 20:44 UTC
Labels: bug
