### ISSUE TITLE
Note lines are duplicating on editing the note

### ISSUE THREAD

**Issue by galakhyati** [Automattic/simplenote-android#596] opened 2018-10-30 17:19 UTC
#### one report:
1. The issue has happened 3 times. The first time I thought it was because of a new Android keyboard I had installed. However, the problem recurred after I switched back to the stock one.
2. I see it happen. Interestingly once when I was trying to delete the extra lines on the phone, it was duplicating a different line further down the note.
3. It happens to the same note every time. It's a pinned to-do list that is reasonably large, ~7,300 characters (inc spaces)

#### another report:
Lines got duplicated thousands of times twice for one person. In their case it was not the same note both times.

#### Simplenote version
v1.6.5-1.6.6

internal reports:
#1522298-zen
#1730598-zen

**Comment by msilbers** [comment] 2018-11-18 17:51
(moved this issue from the iOS repo as it was an Android report)

also reported in #1572664-zen with a published note example in the ticket

**Comment by GeoJunkie** [comment] 2018-11-30 15:40
> also reported in #1572664-zen with a published note example in the ticket

This user reported a repeat of the error in #1608189-zen with additional screenshots

**Comment by thabotswana** [comment] 2019-04-07 06:20
Another reported in #1934477-zen

**Comment by bummytime** [comment] 2019-05-07 21:34
@theck13 This might be a good issue to investigate soon. Thoughts?

**Comment by theck13** [comment] 2019-05-07 22:26
I’ll do a quick spike to see if anything jumps out.

**Comment by theck13** [comment] 2019-05-07 23:59
From the tickets referenced above, there is very little information to help troubleshoot the issue.  Only one ticket has the device make, device model, Android version, and Simplenote version listed (Huawei Honor 9 on Android 8.0 with Simplenote 1.6.5).  There isn't much about the steps to reproduce the issue either.  The only similarity seems to be that the issue occurs when using multiple devices on different platforms.  That leads me to think there are syncing conflicts that are not resolved correctly, but I haven't been able to reproduce the issue at all.

There were some sync issues reported in the past (https://github.com/Automattic/simplenote-android/issues/243, https://github.com/Automattic/simplenote-android/issues/290, https://github.com/Automattic/simplenote-android/issues/350) that were fixed with https://github.com/Automattic/simplenote-android/pull/554 and included in the [Simplenote 1.6.6 release](https://github.com/Automattic/simplenote-android/releases/tag/v1.6.6).  However, I'm not certain the syncing issues resolved in https://github.com/Automattic/simplenote-android/pull/554 are related since those describe overwriting content rather than duplicating content as reported in this issue.

My first recommendation would be to ensure the users have updated the app to the latest release, Simplenote 1.7.0.  That way we can at least rule out the syncing issues fixed since Simplenote 1.6.6 and thereafter.  Second, determining the device make, device model, Android version, and Simplenote version from these reports would be great.  Also, any detailed information on how to reproduce the issue would be very helpful.

**Comment by mgalbritton** [comment] 2019-06-11 01:33
Another report of this bug in an [Android review](https://play.google.com/apps/publish?account=7957760354032996428#ReviewDetailsPlace:p=com.automattic.simplenote&reviewid=gp:AOqpTOHmWZ-wk1VZ7S_-uP6jVXndl0fUI4PP_oGXoadTmeOutyMP17kmk7Y_erGhZBgeXMyyQocd04VJKkXik4c)

Info: 
Simplenote version: 1.7.0
Device: DROID Turbo 2 (kinzie)
Android version: 7.0

**Comment by msilbers** [comment] 2019-07-28 22:43
This has been reported again by a user, awaiting more details and will add those below

information so far:
- Android device
- text "WPS++" duplicated 34,000 times at least
- image: https://cloudup.com/cjBlZCTrQ_F

internal ticket reference: #2211502-zen

**Comment by msilbers** [comment] 2019-07-28 22:46
This has been reported again by a user on Android. I've added relevant details below but I've asked for more

information so far:

- Android device
- text duplicated over 100 times
- Asus Zen One Zoom 3
- Android 8 patch level March 5 2019
- Software Information, Baseband kernel version build number etc WW_80.30.76.74_20190319
- ASUS_Z01HDA

internal ticket reference: #2209246-zen

**Comment by sandymcfadden** [comment] 2019-07-31 09:45
Details for the above comment https://github.com/Automattic/simplenote-android/issues/596#issuecomment-515801484

Samsung Galaxy s10e, SM-G970F
Android 9
version 8.1.2

**Comment by fstath** [comment] 2019-08-21 09:41
Another report on Twitter. The word `Dr.` was repeated 30 times. They resolved it by copying the contents to a new note and deleting the problematic one.

Phone: Samsung J7
Simplenote app version: 1.8.2

Twitter conversation: https://twitter.com/soaked2thebone/status/1163954766323449856
Reply link (Chiron only): https://reply.buffer.com/conversations/XVyBDfpB1wAB8dvG

**Comment by charliescheer** [comment] 2019-09-05 00:07
Another report here #2316812-zen
User details Samsung Galaxy S10+ With Android 9
Simplenote v1.8.2

**Comment by erricgunawan** [comment] 2019-11-09 04:15
Another report 2479679-zen

Waiting for user's details on their device info.

**Comment by arjenbokhoven** [comment] 2019-12-01 03:23
Same problem here. In my case it seems to happen when pasting text: the pasted text got duplicated ad infinitum until I closed the app, restarted it and trashed the note.

Phone: Xiaomi MI A1, Simplenote 2.2, Android 9

**Comment by theck13** [comment] 2019-12-01 03:37
@arjenbokhoven, can you share the note content and pasted text so we can try to reproduce the issue?

**Comment by theck13** [comment] 2019-12-01 04:11
@arjenbokhoven, if you prefer to share the note content and pasted text privately, you can email it to Simplenote support at support@simplenoteapp.com.

**Comment by arjenbokhoven** [comment] 2019-12-01 09:14
@theck13 I'd love to, but the Android app as well as the web app are unresponsive while accessing my Trash (probably due to the note's immense size). 

Basically it happens like this I edit a note, and I accidentally paste text from Android's context copy/paste menu that was leftover from something else I'd done.

Something like this:

This is a note[PASTED TEXT][PASTED TEXT][PASTED TEXT][PASTED TEXT][PASTED TEXT][PASTED TEXT][PASTED TEXT][PASTED TEXT][PASTED TEXT][PASTED TEXT][PASTED TEXT][PASTED TEXT][PASTED TEXT][PASTED TEXT][PASTED TEXT][PASTED TEXT][PASTED TEXT]...

And so on.

As far as I can tell, this seems to occur while pasting inside Markdown-enabled notes.

**Comment by msilbers** [comment] 2020-02-01 18:54
A note was deleted on the Android app, then restored. Upon restoring the note, Simplenote became unresponsive on both Android and the web app. They were able to load the note from the Windows app and there it showed the note was then 123213 lines long, mainly with duplicated text.

(They were able to delete the note from the Windows app and can now load Simplenote on Android and web again.)

reported in #2676739-zen with offending note attached

**Comment by SiobhyB** [comment] 2020-02-24 16:40
There appears to be another case of this in 2737788-zen. The user is using Simplenote across Android and the web app. They ran into problems when editing a note in the web app (they spent several hours on a note only for their changes to disappear when they navigated away from it). After that, they checked their notes in the Android app and saw duplication on one of their older notes:

![Screenshot_2020-02-23-16-49-40-220_com automattic simplenote](https://user-images.githubusercontent.com/2998162/75171863-3baf3a00-5724-11ea-9b4a-18778981b87f.jpg)
 
Their device is an Xiaomi Redme 5 Plus and I'm awaiting confirmation on what version of Simplenote they're running.

**Comment by SiobhyB** [comment] 2020-02-25 08:57
Another report of duplicated/repeating text in 2687996-zen. The user noticed that text they added to a note around three days ago is now duplicated, similar to other reports here. There's a screenshot in the ticket.

They work across both the Android and the web app. They're on a Pixel 3 (running Android 10), using Simplenote 2.3.1. They use the web app on Chrome on Pixelbook Go.

**Comment by msilbers** [comment] 2020-04-16 20:24
"One of my notes crashed today after I pasted a link into it and I still can't access it without crashing the simplenote tab in my browser or the simplenote app on my phone.

For a reason unknown to me, instead of pasting the link I copied (which I did right since I could paste it in another window right away), it copy pasted the first lines of the note itself on a feedback loop."

Android 2.4 and 2.5.1, asked what device
they also use the web app in Firefox

The note has duplicated so much that they cannot open it to fix it, but I am doing so on my end. It's thousands of lines added. 2862689-zen

**Comment by sarahfg** [comment] 2020-05-21 13:36
Another report in #2966798-zen on Android 10. 

> I have just tried to write markdown in simplenote on android snd it's extremely buggy. When I switch between edit abd preview modes, it adds multiple copies of my text to the note

The user finds that the issue has not yet repeated when markdown is turned off.

**Comment by msilbers** [comment] 2020-06-30 16:24
Reported in 3061363-zen
Simplenote Android 2.6

"I had an already written note and I was checking it out and I wanted to add a comma, it was at the end of a line, I added it and as far as I can remember I went out of the note and checked another one and when i left that one I saw in the thumbnail of this first one that the comma I added was in fact a lot of commas and when I clicked the note I saw the commas kept appearing"

It then crashed the app, but they were able to recover and fix the note on the Windows desktop app.

**Comment by sarahfg** [comment] 2020-07-07 13:06
Reported in #3115282-zen
Simplenote Android 2.7

>Sometimes text just disappears, sometimes the copy of some disappeared text block keeps being added multiple times. I added text 190, switched to other app, switched back and 190 became just 1. I added 90, switched to browser and back, and simplenote became adding the 909090, screens of 90909090909090, the note kept growing and growing up to the point when simplenote crashed.

**Comment by msilbers** [comment] 2020-07-19 16:38
reported in 3148488-zen
Simplenote Android 2.7

Motorola G7 Power
Android 9.0 (Motorola PDOS29.114-134-15)

> I *think* it happens when I have the note active and open and then exit or close the Simplenote app (without returning to the Simplenote menu), though I haven't nailed that down 100%. When I return to the note/app the text has repeated and crashes the app, it always seems to happen in the background, never when I am actually looking at or working in the note.

**Comment by msilbers** [comment] 2020-07-23 17:26
reported in 3152256-zen
Simplenote Android 2.7

Android version 9
Moto g6

They opened the note in Android, which they hardly use, and saw text repeated at the end of their note a few dozen times.

**Comment by erricgunawan** [comment] 2020-07-24 05:33
Reported in 3164869-zen

Confirming their device and version.

>  I use the apps on Mac and Android and sometimes the web on Firefox (77.01). My problem is that I have noticed a few apparently random words - sometimes the same word twice together, appearing in notes I haven't accessed for ages.

> I've also found cases when the web version doesn't synch properly to the app on the Mac - fixed by accessing the note once on the Android but it shouldn't be like this. I do hope that there is now some concerted effort on making synch 100% right rather than fussing with color changes or other cosmetics or addons.

**Comment by msilbers** [comment] 2020-08-12 23:46
reported in 3189583-zen

> at one point, when the note tried to sync, the text I added got endlessly repeated, and Simplenote became unresponsive

* It was unpublished
* It did not use markdown (less sure on this one)
* It was created on Android originally, a few days before I tested on it

Environment:

* I use simplenote primarily on:

** Android (Pixel 1, Android 10). Simplenote 2.9-rc-1
** Ubuntu Linux 20.04 (64-bit), on a Dell XPS 13 from 2016. Simplenote 1.21.0

**Comment by msilbers** [comment] 2020-08-13 07:45
reported in  3220291-zen

> Issue occurred just now. I'm on mobile data and wifi is off. I opened the app and tapped on a pinned note at the top. I added some text to it and then tapped the back button and could see in the preview of that note that it did not save what I just wrote. Now when I tapped on the note again to retype what it removed, it generated a TON of that text that I had just entered. I tried to take a screenshot of the note, but it froze my phone. I'm now unable to open that note without it freezing. I can open other notes just fine.

Galaxy S8 running Android 9
asking for Simplenote version


Followup details we asked for:

- Network was fast - I was on mobile data near a window in my house and I don't normally have network issues here.
- I opened it from an app shortcut on my home screen (not a widget and not in the app drawer).
- I did not exit the app or lock the device. I opened the app, tapped on a pinned note quickly, typed the new text (maybe took 5 seconds to type), then tapped the back button on my device (I believe it was the back button from the nav bar, not the back arrow in the app). I immediately noticed the preview of the note did not update to show the additional text and tapped on the same pinned note again maybe 1-2 seconds after viewing the list of notes. When the note opened, I don't remember if I started re-typing the text or if the duplicate text immediately started filling up the note. The duplicate text was the same text I just added earlier in these steps a couple seconds prior.
- Was the note shared with any other users? No
- How long was the note? Very short


ticket includes image of the note along with details about the exact text changes

**Comment by azollafox** [comment] 2020-08-18 17:12
> reported in 3220291-zen

The user here reported that they saw the note at staging.simplenote.com

**Comment by erricgunawan** [comment] 2020-09-05 06:48
Reported on iOS 13.6.1 on mobile and Chrome on desktop in 3282999-zen, so *not* Android

**Comment by sarahfg** [comment] 2020-09-08 16:04
Reported on iOS 13.6.1 on mobile and Chrome on desktop

**Comment by theck13** [comment] 2020-09-08 16:16
@sarahfg, was that comment meant to be in the Simplenote Android repository?  I see you mentioned iOS and Chrome on desktop, which seems like Simplenote iOS and Simplenote Electron.  Is that right?

**Comment by msilbers** [comment] 2020-09-09 16:29
@theck13 it was reported here before we knew what platform, but we hadn't encountered this issue on others, when the user wrote back, turns out it was not Android. I've edited the above comments.

**Comment by theck13** [comment] 2020-09-09 16:37
Thanks for the clarification and updating the comment, @msilbers.

**Comment by reginabally** [comment] 2020-09-25 06:12
Reported in 3343543-zen on Google Pixel 3a, Android 10, app version 2.10 (115).

It was mentioned no copy/paste action was taken during the event, just switching apps.

> YES, went to Twitter amongst other things, when I returned, Simplenote started going mad. Deleting some text, copying and pasting several times over. Occasionally lost text in the past, but never the copy & paste thing

![Screenshot_20200923-215543](https://user-images.githubusercontent.com/40906847/94232645-0fb59a80-ff39-11ea-9130-6a861cfabd17.png)

**Comment by reginabally** [comment] 2021-02-08 05:33
Another report in 3696059-zen. The video recordings can be found in the ticket.

**Comment by thabotswana** [comment] 2021-07-12 09:57
Another report here: 4110365-zen. 

>I found out a little problem about your web app when it runs on Android browser, either Samsung Browser or Google Chrome. When I type sometimes the word duplicates like this - automaticautomatic.

Devices: Samsung Galaxy J2 Prime and Huawei Honor 4c (CHM-U01). 
Operating systems: Android 6.0.1 and Android 5.1.1 respectively. 
Using web app on both devices.

**Comment by CameronMilliken** [comment] 2022-05-13 14:08
> The last note I worked on is doubled.

pc and android, windows 10

2.21

https://woothemes.zendesk.com/agent/tickets/5183523

**Comment by azollafox** [comment] 2022-08-29 13:29
>Since a few days ago, when I type characters, the same characters continue below and the app freezes. I've tested it on both my phone and tablet, so I don't think it's a device issue. Please kindly correct it.

Device: Lenovo Tab M8 Device language: Japanese App version code: 150 App version name: 2.24.1

reviewId=600c8e14-7f01-4ab5-b84b-73e7d27f78f1&corpus=PUBLIC_REVIEWS

**Closed** 2024-05-13 20:08 UTC
Labels: [Type] Bug
