### ISSUE TITLE
Rapidly tapping duplicates the action

### ISSUE THREAD

**Issue by leandroalonso** [Automattic/simplenote-android#774] opened 2019-08-15 16:14 UTC
### Expected
Rapidly tapping the New note button creates only one new note. Similarly, rapidly tapping a note in the list opens it for editing just once.

### Observed
Rapidly tapping the New note button creates two notes at once. Similarly, rapidly tapping a note in the list opens it for editing twice.

### More information

`2276531-ze`

**Comment by theck13** [comment] 2019-08-15 16:17
This is a duplicate of https://github.com/Automattic/simplenote-android/issues/661.

**Closed by theck13** 2019-08-15 16:17 UTC
Labels: bug, duplicate
