### ISSUE TITLE
Duplicated tags

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-android#1713] opened 2024-11-03 09:01 UTC
### Expected
I create a new tag (regardless of Simpenote Windows/Electron or Simplenote Android).

### Observed and Reproduced

- I have created a new tag yesterday on Simpenote Windows/Electron 
- Today, the tag appears duplicated on 
Simpenote Windows/Electron and Simplenote Android).

### The bug has been reported here by various users in 2020, already.
 
Device Make: Samsung Galaxy 
Device Model: A32
Android Version: 10.0.0
Simplenote Version: 2.34 (174)

**Comment by dangermattic** [comment] 2024-11-03 09:02
Thanks for reporting! 👍

**Comment by roundhill** [comment] 2024-12-12 22:28
I think I see what the problem is:

<img width="215" alt="Image" src="https://github.com/user-attachments/assets/ee755b2c-d58c-4f84-846e-7f4fe8f6c7e3" />

The web app is likely the culprit here.

**Comment by roundhill** [comment] 2024-12-12 22:30
Closing in favor of #1394

**Closed as completed by roundhill** 2024-12-12 22:30 UTC
