### ISSUE TITLE
Case sensitive seach for  Cyrillic characters

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/simplenote-android#438] opened 2017-03-15 07:45 UTC
Reported at 3107673-t , seems that  Cyrillic characters (for example, Russian) are case sensitive in the search field. If you're looking for the notes with a certain word, only those notes with the exact same case match will show up.

**Steps to reproduce:**
1 - Switch your input keyboard to Russian.
2 - Create two notes with the same string but different casing, for example: `Я люблю гречку` and `Я Люблю гречку`
3 - Search for one of the strings, foe example `люблю` . Only one note shows up instead of both.

In English works, and also other versions, the problem seems to be just in Android.

**Comment by rachelsquirrel** [comment] 2017-04-28 07:11
Dupe of https://github.com/Automattic/simplenote-android/issues/278

**Closed by rachelsquirrel** 2017-04-28 07:11 UTC
Labels: bug
