### ISSUE TITLE
Monochrome/Themed Icon

### ISSUE THREAD

**Issue by NielSync** [Automattic/simplenote-android#1633] opened 2024-02-02 08:57 UTC
![Screenshot_20240202-112730~2.jpg](https://github.com/Automattic/simplenote-android/assets/20804647/deb0cc46-5837-4cef-bb53-85651bf92751)

**Comment by roundhill** [comment] 2024-02-05 22:16
👋 Dupe of #1565

**Closed as completed by roundhill** 2024-02-05 22:16 UTC
Labels: feature request
