### ISSUE TITLE
App crashes repeatedly on Samsung Galaxy s7 android phone

### ISSUE THREAD

**Issue by eurello** [Automattic/simplenote-android#484] opened 2017-12-26 19:09 UTC
A user reports that the app repeatedly crashes on his Android phone. Works fine on his tablet and PC. Updated to version 1.5.7 and uninstalled and reinstalled with no change. 

They included a video of the crashing with error messages in ZD ticket #862099; not sure if I should include that in the public repo. In the video, they reinstall Simplenote, and as soon as they try to open it, it crashes with message "Simplenote has stopped." They try once more and get, "Simplenote keeps stopping" 

Are there additional troubleshooting steps I should suggest here?

**Comment by maheshgaya** [comment] 2017-12-27 04:57
There's no v1.5.7 for Android (yet)

**Comment by roundhill** [comment] 2017-12-27 05:30
@eurello can you have them send in a crash report? It's the 'Send feedback' button after the app crashes.

@maheshgaya looks like our 1.5.6 was released as 1.5.7 :) I'll update the tag.

**Comment by eurello** [comment] 2017-12-27 12:46
Sure thing, I've asked them. Will update when they reply.

**Comment by kamlesh08** [comment] 2018-04-28 11:00
Not sure if this is the right place.
The issue was also occurring to me. The app was crashing after the installation and whenever I tried to open it, it said: "Simplenote has stopped working". But after the 1.5.8 was released, it has worked perfectly fine.

**Comment by theck13** [comment] 2019-05-24 18:25
I cannot reproduce that behavior.  Feel free to reopen this issue if you can.

**Closed by theck13** 2019-05-24 18:25 UTC
Labels: crash
