### ISSUE TITLE
Weird Repetitions while Typing

### ISSUE THREAD

**Issue by druesome** [Automattic/simplenote-android#443] opened 2017-04-24 16:55 UTC
We got several users who experienced an odd bug wherein they write in a note and press return, then as they begin typing a another line, the app freezes and copies of the previous line multiply by the hundreds or thousands.

One user did not have the app open in another device, while one appears to have had it open in the Android and Windows apps at the same time.

I'm not able to replicate this in my Android device.  These seem to happen randomly.

For reference, here are the ticket IDs:

- #3152770-t
- #3115251-t
- #3174093-t

Thank you!

**Comment by rahul020691** [comment] 2017-10-26 13:03
User with  Simplenote 1.5.6 on Oreo (Android 8.0). also facing the issue:
ticket
https://woothemes.zendesk.com/agent/tickets/751092

**Comment by detlefholtz** [comment] 2018-11-15 12:19
User is reporting a very similar issue. Waiting for them to follow up with more information.

**Comment by theck13** [comment] 2019-12-18 19:53
This looks like a duplicate of https://github.com/Automattic/simplenote-android/issues/596.  Since https://github.com/Automattic/simplenote-android/issues/596 has more details, I'll close this one.

**Closed by theck13** 2019-12-18 19:53 UTC
Labels: bug
