### ISSUE TITLE
Cutting and pasting text in the same note

### ISSUE THREAD

**Issue by ezebecke** [Automattic/simplenote-android#649] opened 2019-02-28 21:36 UTC
They are reporting that in the latest app update for Android when they cut text in a note and paste it in the same note, the app will close. This happens to them when they are using version 1.7. They are now using v1.6.7
The user says they can't update their Android version anymore. 

Device: LG S3 Model LG D-722
I haven't seen this bug anywhere else, so it might be specific to their device. I suggested keeping the version v1.6.7 for now and try to update their Android version when an update is available.

#### Simplenote version

1.7.0

#### OS version

Android 5.1.1

Ref: 1798252-zd

**Comment by theck13** [comment] 2020-12-03 15:47
I can't reproduce that behavior on the latest version or the version in question.  Unfortunately, we don't support Android 5.1.1 anymore.  Devices using an Android version before 6.0 can use any Simplenote Android up to 1.8.2.  Versions after that require Android 6.0 or later.  Simplenote Android 1.8.2 can be download [here](https://github.com/Automattic/simplenote-android/releases/tag/1.8.2) and all released versions can be found [here](https://github.com/Automattic/simplenote-android/releases).  Since Android 5.1.1 is no longer and the SImplenote Android versions in question are almost two years old, I'm going to close this issue as `wontfix`.

**Closed by theck13** 2020-12-03 15:47 UTC
Labels: bug
