### ISSUE TITLE
Organizing notes

### ISSUE THREAD

**Issue by dokker** [Automattic/simplenote-android#424] opened 2017-02-06 10:32 UTC
Would you consider to implement **one level folder support** for better organization of notes?
If the folders implementation beyond the barriers of simplicity, at least **nested tags** support?

**Comment by pihentagy** [comment] 2017-02-07 09:02
Maybe duplicate of #379

**Comment by ericbrandwein** [comment] 2017-11-30 03:33
You *could* emulate nested tags by just using a tag only if other is present, but that isn't the best approach I believe.

**Comment by theck13** [comment] 2019-05-22 04:02
Thanks for the suggestion!  I have added it to our feature requests.

**Closed by theck13** 2019-05-22 04:02 UTC
Labels: feature request
