### ISSUE TITLE
App Starts with White Background in Dark Theme

### ISSUE THREAD

**Issue by jivox92362** [Automattic/simplenote-android#884] opened 2019-11-17 00:53 UTC
The app initializes with a white container, brightly flashing into your eyes at night.

### Expected
The app initializes with a transparent or black container.

### Observed
The app initializes with a white container.

### Reproduced
at night, in dark mode
1. Get in line at Sparrow, LA's hottest club
2. Open Simplenote to check what you got going on tomorrow
3. The screen flashes like a camera flash
4. Girl behind you yells about you taking a photo of her
5. You tell her you were checking your schedule on Simplenote
6. She asks wtf simplo? why you takin photo of me?
7. You just say your iPhone got confused about being in dark mode for a second

**Comment by BitsInMyBlood** [comment] 2020-01-04 01:40
The application preview window background color needs to be changed to black only if dark mode is enabled, or always ?

**Comment by theck13** [comment] 2020-01-04 03:17
The startup background should match the `mainBackgroundColor` attribute (i.e. `background_dark` for Dark and ``background_light` for Light).

**Comment by manu-chroma** [comment] 2020-02-01 20:43
Hi, I'm interested in taking up this issue. 

Problem is, I'm not able to reproduce this issue on my android device. I suppose this issue present on simplenote-ios? (since the description says iPhone)

**Comment by theck13** [comment] 2020-02-01 20:55
The iPhone reference is just a joke or mistake.  This is an Android issue.  See the animation below for illustration.

<a href="https://user-images.githubusercontent.com/3827611/73598844-5e21af00-44fa-11ea-9a6a-1b22d587bb7f.gif"><img src="https://user-images.githubusercontent.com/3827611/73598844-5e21af00-44fa-11ea-9a6a-1b22d587bb7f.gif" width="300"></a>

**Comment by adityabhaskar** [comment] 2020-02-18 19:05
Hi

I'll work on this bug unless someone's already on it.

Cheers!

Adi

**Comment by adityabhaskar** [comment] 2020-02-19 15:55
I'm unable to replicate this issue. I tried on a device (Pixel with API 29) and emulators (Pixel 3XL with API 29, and Nexus 5X with API 25).

I am quite confident that this behaviour is not due to missing dark mode background resource for startup window. The theme setup is correct (relevant lines below the fold). 

My hypothesis is that the white splash is occurring because the `AppCompatDelegate.setDefaultNightMode` is called in `ThemeUtils.setTheme` from `NotesActivity.onCreate`. [The recommendation](https://medium.com/androiddevelopers/appcompat-v23-2-daynight-d10f90c83e94) is to call `setDefaultNightMode` in `Application.onCreate`.
 
In our case, the Application class (`Simplenote.java`) doesn't know which night mode to apply, so it uses the default `MODE_NIGHT_NO` with white background till the Activity overrides it in its onCreate. 

If the hypothesis is correct, the visible flash must only happen when the OS is under load so the transition from Application launch to Activity.onCreate is slow.

_Suggested solution: Extract the `setDefaultNightMode` call from `ThemeUtils.setTheme` and call the extracted method in `Simplenote.onCreate`._

---

The lines below indicate that the theme setup is correct:

In Manifest:

```
    <application
        ...
        android:theme="@style/Theme.Simplestyle">
```

In `night/styles.xml`:
```
    <style name="Base.Theme.Simplestyle" parent="Theme.MaterialComponents.DayNight.NoActionBar">
        ...
        <item name="android:windowBackground">@color/background_dark</item>
        ...
    </style>

    ...

    <style name="Theme.Simplestyle" parent="Base.Theme.Simplestyle">
        <item name="android:statusBarColor">@android:color/transparent</item>
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:windowLightStatusBar">false</item>
    </style>
```


In `colors.xml`:

```
    <color name="background_dark">@color/background_dark_1</color>
    
    ...
    
    <color name="background_dark_1">#1f2123</color>
```

**Comment by BitsInMyBlood** [comment] 2020-02-19 15:58
It is replicated for me... Not sure why you're not seeing it.

**Comment by adityabhaskar** [comment] 2020-02-19 16:15
> It is replicated for me... Not sure why you're not seeing it.

Will you be able to test it with [this branch](https://github.com/adityabhaskar/simplenote-android/tree/issue/884-app-starts-with-white-background-in-dark-theme). 

I've moved the `setDefaultNightMode` to the Application class. If this resolves the issue, it would indicate that the hypothesis is correct, and I'll send in the PR.

**Comment by adityabhaskar** [comment] 2020-02-19 18:23
Sharing @theck13 's comment from the PR. It describes in detail how to replicate the issue.

> I'm still seeing the light screen on launch before the app is changed to the Dark theme. Specifically, it occurs on devices and emulators below API 29 and with API 29 if Android's Dark mode is not enabled. Android's Dark mode appears to handle the Dark theme correctly and the screen is dark on launch if the Dark theme is selected in Simplenote. If the Light theme is selected in Simplenote and Android's Dark mode is enabled on the device running API 29, the dark screen is shown on launch before the app is changed to the Light theme. I'm seeing the same behavior before and after the changes in this pull request.

**Comment by adityabhaskar** [comment] 2020-02-19 18:52
There is a discussion of solution approaches to this issue [here on SO](https://stackoverflow.com/a/23411159/1078008).

Two relevant approaches are:
1. Create a special application theme which has a background (splash) that may be acceptable in both dark and light themes. 
 The splash theme may have the Simplenote logo on a neutral or brand colour as background. The splash theme is then applied to the application. Activities will override it with the current app theme.
2. Disable the splash screen entirely by adding the below code to app theme.  
  This resolves the flash, but adds a noticeable delay between the icon tap and the appearance of activity window.
  `<item name="android:windowDisablePreview">true</item>`

I have tested both approaches on my local device, and both work. I recommend taking the first approach, but it needs design input for the night-mode-neutral splash screen.

**Comment by theck13** [comment] 2020-02-19 21:06
We can use a simplified version of the [`activity_authentication` layout from the Simperium library](https://github.com/Simperium/simperium-android/blob/538aad6a0c612cd2f3022ae5568d52fa6900e6be/Simperium/src/main/res/layout/activity_authentication.xml), which is used for the Simplenote authentication screen.

```xml
<?xml version="1.0" encoding="utf-8"?>

<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:background="?attr/backgroundColor"
    android:layout_height="match_parent"
    android:layout_width="match_parent">

    <ImageView
        android:contentDescription="@string/app_name"
        android:layout_centerInParent="true"
        android:layout_height="@dimen/width_logo"
        android:layout_width="@dimen/width_logo"
        android:src="@drawable/ic_simplenote_blue_24dp">
    </ImageView>

</RelativeLayout>

```

Simplenote's logo can be used with negative space making it so the same image can be used for both ***Light*** and ***Dark*** themes.

**Comment by adityabhaskar** [comment] 2020-02-20 17:12
For the splash screen style, we need to set `android:windowBackground` to a drawable or a colour. The system doesn't inflate a layout for that. I created a drawable and set it as the launch splash screen. This is what the splash screen looks like:
  
In system dark mode, and in system light mode on API 27+  
<img src="https://user-images.githubusercontent.com/2292388/74959857-3b9cfa80-5403-11ea-972a-edc930e76fc0.png" width="100">  
In system light mode below API 25 (can't change navigation bar icons before API 27)  
<img src="https://user-images.githubusercontent.com/2292388/74959860-3cce2780-5403-11ea-9530-a6f25c5ac018.png" width="100">

We can use different background colours for the background. But the background colour will follow the system night mode (light pre API 29, and user selected on API 29+), not the night mode specified in app.  

---

`@drawable/splash_background`:

```
<layer-list xmlns:android="http://schemas.android.com/apk/res/android"
    android:opacity="opaque">
    <item android:drawable="@color/blue"/>
    <item
        android:width="96dp"
        android:height="96dp"
        android:drawable="@drawable/ic_simplenote_24dp"
        android:gravity="center"/>
</layer-list>
```

`values/styles`:
```
    <style name="Theme.Simplestyle.Splash">
        <item name="android:windowBackground">@drawable/splash_background</item>
        <item name="android:statusBarColor">@color/blue</item>
        <item name="android:windowLightStatusBar">false</item>
        <item name="android:navigationBarColor">@color/blue_30</item> <!-- Needs to be light enough for dark navigation icons to be visible, but not too light to contrast against the splash background -->
    </style>
```

`values-night/styles`:
```
    <style name="Theme.Simplestyle.Splash">
        <item name="android:windowBackground">@drawable/splash_background</item>
        <item name="android:statusBarColor">@color/blue</item>
        <item name="android:windowLightStatusBar">false</item>
        <item name="android:navigationBarColor">@color/blue_dark</item>
    </style>
```

`values-v27/styles`:
```
    <style name="Theme.Simplestyle.Splash">
        <item name="android:windowBackground">@drawable/splash_background</item>
        <item name="android:statusBarColor">@color/blue</item>
        <item name="android:windowLightStatusBar">false</item>
        <item name="android:navigationBarColor">@color/blue_dark</item>
        <item name="android:windowLightNavigationBar">false</item>
    </style>
```

**Comment by theck13** [comment] 2020-02-20 23:40
Good idea using the blue background with the white Simplenote logo!  I think we can inherit the `Theme.Simplestyle.Splash` style from `Theme.Simplestyle.Passcode`.  That way the splash screen with fade into the passcode screen well, if passcode lock is enabled.  Even if passcode lock is disabled, the `blue` color works well for both ***Light*** and  ***Dark*** themes regardless of Android's Dark mode being enabled or disabled.

I tested that on API 23, 24, 25, 26, 27, 28, and 29.  See the screenshots and animation below for illustration.

![splash](https://user-images.githubusercontent.com/3827611/74986674-c1ff0f80-53f6-11ea-92f9-f26d8a95de0a.png)

<a href="https://user-images.githubusercontent.com/3827611/74990070-7c931000-53ff-11ea-942a-96fd8752c686.gif"><img src="https://user-images.githubusercontent.com/3827611/74990070-7c931000-53ff-11ea-942a-96fd8752c686.gif" width="300"></a>

@SylvesterWilmott, what do you think?

**Comment by SylvesterWilmott** [comment] 2020-02-21 00:43
This looks great! Thanks @jivox92362 and @theck13 

I think the logo looks quite large on screen, can we try 72dp which matches with our empty state icon sizes?

**Comment by theck13** [comment] 2020-02-21 01:58
Just for comparison, the blue Simplenote logo on the authentication screen and the gray Simplenote logo when a note is not selected on tablets are 96dp.

Authentication|Tablet
-|-
![Screenshot_1582250128](https://user-images.githubusercontent.com/3827611/74997260-ec5ec600-5412-11ea-950e-a053b96dde3f.png)|![Screenshot_1582250211](https://user-images.githubusercontent.com/3827611/74997264-eec12000-5412-11ea-941f-b7d9e4fdb47a.png)

**Comment by SylvesterWilmott** [comment] 2020-02-21 16:44
>Just for comparison, the blue Simplenote logo on the authentication screen and the gray Simplenote logo when a note is not selected on tablets are 96dp.

That's a good point. Even so, for a splash screen it feels large, I'd still be interested in seeing a 72dp version.

**Comment by adityabhaskar** [comment] 2020-02-21 23:25
Here it is, splash with 72dp logo:

<img src="https://user-images.githubusercontent.com/2292388/75079634-5190e500-5501-11ea-9bf7-23d397a7013a.png" width=200>

**Comment by theck13** [comment] 2020-02-21 23:36
Here's a comparison between 96dp, 72dp, and the empty views.

![splash_comparison](https://user-images.githubusercontent.com/3827611/75080126-4d94a100-54c8-11ea-9fd4-440d71f4bc5c.png)

**Comment by adityabhaskar** [comment] 2020-02-24 10:59
> Here's a comparison between 96dp, 72dp, and the empty views.
> 
> ![splash_comparison](https://user-images.githubusercontent.com/3827611/75080126-4d94a100-54c8-11ea-9fd4-440d71f4bc5c.png)

@theck13 how do you take/combine these screenshots? It's a handy tool.

**Comment by theck13** [comment] 2020-02-24 16:02
I usually take the screenshots on an emulator using the ***Command*** + ***S*** keyboard shortcut.  Once I have all the screenshot files, I use a script I created to combine them into one image.  I wrote a [post](https://heckofanapp.com/2020/02/24/screenshot-script) with all the details.  Feel free to leave a comment there if you have any questions.

**Comment by adityabhaskar** [comment] 2020-02-24 16:21
Thanks! That's really helpful.

Any word on 72dp vs 96dp icon?

**Comment by SylvesterWilmott** [comment] 2020-02-24 17:44
72 looks good to me!

**Comment by theck13** [comment] 2020-02-25 16:24
Closed by https://github.com/Automattic/simplenote-android/pull/960.

**Closed by theck13** 2020-02-25 16:24 UTC
Labels: [priority] low, enhancement, good first issue

**Comment by adityabhaskar** [comment] 2020-02-25 17:11
A relevant note: You may want to add similar splash themes to the WordPress and WooCommerce apps before while the dark theme is being implemented in them.

**Comment by theck13** [comment] 2020-02-25 17:37
Good idea!  Can you create an issue in both [WooCommerce](https://github.com/woocommerce/woocommerce-android/issues/new/choose) and [WordPress](https://github.com/wordpress-mobile/WordPress-Android/issues/new) repositories for that?  Referencing this issue may help as well.
