### ISSUE TITLE
Please add "Sign in with Google" option

### ISSUE THREAD

**Issue by Donboscow** [Automattic/simplenote-android#858] opened 2019-10-26 13:13 UTC
### What
***Please kindly add "Sign up & Sign in with Google Account" option***

### Why
***Then we can easily sign in Simplenote from desktop, mobile & web without any hassle***

**Comment by theck13** [comment] 2019-10-26 13:54
Closing since this is a duplicate of https://github.com/Automattic/simplenote-android/issues/664.

**Closed by theck13** 2019-10-26 13:54 UTC
Labels: duplicate, feature request

**Comment by Donboscow** [comment] 2019-10-26 14:23
Any ETA? @theck13

**Comment by belcherj** [comment] 2019-10-26 15:32
No eta.
