### ISSUE TITLE
Pressing 'Right Arrow' Key Blanks Out Note Editor

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-android#472] opened 2017-11-01 18:37 UTC
User report:

https://cloudup.com/cnp8V942ABL

I wonder if that is switching to the markdown view without triggering the code that renders the markdown content?

**Comment by hotchemi** [comment] 2019-01-27 19:51
Can I possibly grab the issue? 👀

**Comment by msilbers** [comment] 2019-02-03 21:46
This was reported again in #1771221-zen

"When I tap “▷ button” at the just end of a sentence, app falls into white-out screen where I can write nothing."

**Comment by abhifocals** [comment] 2019-05-15 20:51
I cannot repro this issue. Should I close it?

**Comment by theck13** [comment] 2019-05-24 17:52
I can reproduce this issue.  @roundhill is correct; pressing the right arrow key on a keyboard moves from _*Edit*_ to the _*Preview*_ tab whether markdown is enabled or not.  See the animation below for illustration.

<a href="https://user-images.githubusercontent.com/3827611/58347103-35e59a80-7e1a-11e9-8dba-bbcddf6d1fbd.gif"><img src="https://user-images.githubusercontent.com/3827611/58347103-35e59a80-7e1a-11e9-8dba-bbcddf6d1fbd.gif" width="360"></a>

Follow the steps below using the stock Android emulator to reproduce the behavior.

0. Use emulator with keyboard input enabled.
1. Tap _*New Note*_ floating action button.
2. Enter "Test" in new note.
3. Notice "Test" is displayed.
4. Notice software keyboard is shown.
5. Notice no actions in app bar are disabled.
6. Press right arrow key on hardware keyboard.
7. Notice software keyboard is dismissed.
8. Notice "Test" slides to left.
9. Notice "Test" is not displayed.
10. Notice some actions in app bar are disabled.
11. Press left arrow key on keyboard.
12. Notice "Test" slides from left.
13. Notice "Test" is displayed.
14. Notice no actions in app bar are disabled.

**Comment by klockey** [comment] 2020-03-09 16:22
Could not reproduce error.  Using MacBook Pro (17-inch, Early 2011) 2.2 GHz Intel Core i7.

**Comment by itsTallulah** [comment] 2020-06-18 13:16
Can reproduce in Android 10 with EMUI 10 with current system & Simplenote updates.
Witha bluetooth keyboard, rightarrow key at the end of any note navigates to an empty pane. Sometimes leftarrow can escape it, sometimes not after other keypresses. Screen taps in this blank pane do nothing.

![simplenotekeyboard](https://user-images.githubusercontent.com/57402753/85024601-37dd7280-b16e-11ea-97d3-fc89d6d3a725.gif)

Sorry the gif isn't as neat as a screencast!

**Closed** 2020-12-14 15:25 UTC
Labels: bug, good first issue
