### ISSUE TITLE
Syncronization issue on Nexus 5

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/simplenote-android#350] opened 2016-04-09 16:06 UTC
I had a user email us with the following bug report that affects synchronization on the Nexus 5 android version.  They left a pretty complete report so I am quoting it here with some edits

> There is a  difference in behaviour is that on the Nexus 5, going to the homescreen then re-opening Simplenote by tapping its icon in the launcher takes me to the list of notes.
> On the other Android device I tested on, when I go to the homescreen and re-open Simplenote from the launcher, it takes me directly to the note I was previously editing, skipping the list of notes.
> 
> This distinction is important, as to reproduce the sync issue on the Nexus 5, you need to re-open Simplenote from the recent apps list instead of tapping its icon in the launcher. The problem I describe only occurs if the note is already open when returning to the Simplenote app on Android.
> 
> Steps to reproduce on the Nexus 5 and stock Android 6.0.1:
> 1. In the Simplenote for Mac client (X), create a new note. I called it "Test note".
> 2. In the Simplenote for Android client (A), open the "Test note".
> 3. In X, append a new line with the text "X1". Observe that it syncs correctly to A.
> 4. In A, append a new line with the text "A1". Observe that it syncs correctly to X.
> 5. Press the Home button on A.
> 6. In X, append a new line with the text "X2".
> 7. Press the Recents button on A, then select Simplenote from the recent apps list.
> 8. Observe that the note now showing on A is missing the "X2" line.
> 9. In A, append a new line with the text "A2". Observe that in X, the "X2" line disappears, replaced with the "A2" line.
> 10. Press the Home button on A.
> 11. In X, append a new line with the text "X3".
> 12. Press the Recents button on A, and select Simplenote from the recent apps list.
> 13. Observe that the note now showing on A is missing the "X3" line.
> 14. In X, append a new line with the text "X4".
> 15. Observe that in X, both the "X3" and "X4" lines disappear after syncing. Observe that no changes show on A. 

Reported in 2616443

**Comment by roundhill** [comment] 2018-08-27 15:58
Dupe of #243

**Closed by roundhill** 2018-08-27 15:58 UTC
Labels: duplicate
