### ISSUE TITLE
Note Titles Sometimes Don't Appear in Notes List

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/simplenote-android#626] opened 2019-01-23 15:11 UTC
User reports that on occasion, the note title will no longer show in the note list. The issue happens intermittently. We haven't been able to reproduce it. 

#### Simplenote version
 1.6.7

#### OS version
Oreo 
Moto G5

#### Screenshot / Video
![sn-screenshot](https://user-images.githubusercontent.com/19782997/51615945-a8874d80-1eee-11e9-9c1f-873ca55b8222.png)

Reported in #1702083-zen

**Comment by potahto** [comment] 2019-04-14 21:24
I also see this behavior — Android 8.1.0 Oreo, Moto G5S+, Simplenote 1.7.0. I don't code, but is there anything I can do to help debug it further?

**Comment by theck13** [comment] 2019-05-29 06:55
@potahto, if you have any details about how to reproduce this behavior, that would be greatly appreciated!  Approximately, how many notes are in the list when this happens?  Does it happen while you're scrolling or when first opening the app or otherwise?  Step-by-step instructions would be great too.

**Comment by potahto** [comment] 2019-05-31 07:59
Wow — come to think of it I've actually not seen this behavior for a while
now that 1.7.0 is running. Maybe some other change fixed it. Sorry I can't
be more helpful. I'm thankful for the work you all do and if I see the
behavior again I'll try to capture that info!

**Comment by theck13** [comment] 2019-05-31 14:52
Since this doesn't seem to be occurring any longer and I can't reproduce it, I'll close this issue.  Thanks, @potahto!

**Closed by theck13** 2019-05-31 14:52 UTC
Labels: bug
