### ISSUE TITLE
Back Navigation from Trash screen

### ISSUE THREAD

**Issue by AmandaRiu** [Automattic/simplenote-android#696] opened 2019-06-07 21:51 UTC
### Expected
Opening an item from the "trash" list and clicking back returns to the trash list.

### Observed
Opening an item from the "trash" list and clicking back takes the user back to the notes list.

### Reproduced
1. Open menu drawer, select "trash"
2. Tap on an item in the trash list, the item opens
3. Click back in the menu or on the device, "All Notes" appears.

<img src="https://user-images.githubusercontent.com/5810477/59135411-0bc4ca00-893c-11e9-952e-a5642e869a70.gif" width="350"/>

**Comment by theck13** [comment] 2019-06-10 14:31
I'm not able to reproduce that behavior with a Google Pixel 3 device on Android 9.0.0 or a Google Pixel 2 emulator on Android 7.1.1 with Simplenote 1.7.0.  I tried tapping the back arrow in the app bar and the back button in the navigation bar.  See the animation below for illustration.

<img src="https://user-images.githubusercontent.com/3827611/59154592-807a3000-8a32-11e9-9dfd-71fd71fb8450.gif" width="300">

Are there any other details to help reproduce the back arrow/button showing ***All Notes*** from a trashed note?

**Comment by AmandaRiu** [comment] 2019-06-10 21:37
Hi @theck13, it happened on an emulated device (Pixel 3a) running Android P.

**Comment by theck13** [comment] 2019-06-10 21:53
I tested on a Google Pixel 3 running Android 9.0.0 with device and emulator again without being able to reproduce it.  Also, I don't see an option for a Pixel 3a image with the stock emulator.  Are you using the stock emulator or something else?

**Comment by theck13** [comment] 2019-12-06 21:02
@AmandaRiu, is it possible you had the "Don't keep activities" setting enabled?  If so, that might be why you saw this behavior since the note editor is a separate activity than the note list, tapping a note would kill the note list activity, and returning to the note list would show ***All Notes*** since that is the default item selected when the note list activity is initialized.  To confirm that's what's happening, does the note list show ***All Notes*** when returning to the note list after tapping a note with any other item selected in the navigation drawer (e.g. ***Untagged Notes*** or any user-defined tag)?

**Comment by theck13** [comment] 2019-12-13 20:00
After discussing this with @AmandaRiu, the behavior was caused by the "Don't keep activities" setting.  Therefore, I'll close this issue since that's expected behavior due to the operating system.

**Closed by theck13** 2019-12-13 20:00 UTC
Labels: bug
