### ISSUE TITLE
Synchronisation problems

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-android#290] opened 2015-05-29 07:17 UTC
A user reports that when they delete a note from the web app, it's still visible in Android when they open it and then gets re-synced with the web app and appears there again even though it was deleted. I can't reproduce this but wanted to record it somewhere anyway.

They don't use tags and only notice the problem when creating or editing notes in Android.

https://simplenote.desk.com/agent/case/62770

**Comment by gracie** [comment] 2016-11-07 14:47
Similar issue reported in #2908275-t.

Scenario: Web app is open in Windows and the Android app open on their phone (it does not happen when only one app is open).

What happens: They edit the note, then it syncs back to an old version of the note on both apps. They can see their edits in the history.

**Comment by roundhill** [comment] 2018-08-27 15:57
Dupe of #243

**Closed by roundhill** 2018-08-27 15:57 UTC
Labels: bug, duplicate
