### ISSUE TITLE
Markdown "code fences" not supported on android app

### ISSUE THREAD

**Issue by frabert** [Automattic/simplenote-android#447] opened 2017-05-18 11:25 UTC
While I can successfully enter and preview github-style codefences from the windows app, they do not preview correctly on android, they basically get ignored.

**Comment by alexjgustafson** [comment] 2017-06-17 14:16
3262159-t

**Comment by theck13** [comment] 2019-05-23 23:17
This is a duplicate of https://github.com/Automattic/simplenote-android/issues/411.

I confirmed the behavior works by preceding and succeeding the code block with either <code>```</code> or <code>~~~</code> on a separate line.  See the screenshots below for illustration.

![markdown](https://user-images.githubusercontent.com/3827611/58189583-04cd6480-7c78-11e9-9dfc-0a0e852596ab.png)

**Closed by theck13** 2019-05-23 23:17 UTC
Labels: duplicate, enhancement
