### ISSUE TITLE
Issue logging in with word press. 

### ISSUE THREAD

**Issue by NicolasChelico** [Automattic/simplenote-android#1648] opened 2024-04-14 23:37 UTC
### Reproduced
example:
1. Launch Simplenote
2. Press on login with wordpress

Device Make: Google
Device Model: Pixel 3
Android Version: 14.0.0
Simplenote Version: 2.8.0

**Comment by dangermattic** [comment] 2024-04-14 23:37
Thanks for reporting! 👍

**Comment by roundhill** [comment] 2024-05-13 14:27
Dupe of #1649

**Closed as completed by roundhill** 2024-05-13 14:27 UTC
