### ISSUE TITLE
No spelling correction

### ISSUE THREAD

**Issue by thabotswana** [Automattic/simplenote-android#1411] opened 2021-07-12 11:08 UTC
### Expected
I would expect when I make a spelling mistake, the app will help me auto-correct it, or at least indicate a spelling error. 

### Observed
Nothing happens when I make a spelling mistake on the notes, even though spell check is enabled on my mobile device settings.

### Reproduced
**Note:** The issue was originally reported in 4110365-zen but I'm able to replicate this on my device.

For example:
1. Make sure spelling correction is enabled on your device.
2. Open Simplenote app
3. Create a new note
4. Type a wrong word, e.g. contry
5. See that the app does nothing with the wrong word.

https://user-images.githubusercontent.com/35628116/125277705-11a6e980-e312-11eb-8f27-de22f922f062.mp4

Device Make: Samsung
Device Model: Galaxy S9+ 
Android Version: 10.0.0
Simplenote Version: 2.18

**Comment by pachlava** [comment] 2021-07-13 12:30
@thabotswana thanks for creating an issue 👋 From the video it looks like the issue is related to Microsoft SwiftKey.

While using the native Android keyboard, the spell check settings are defined in the phone `Settings`, and they do work, but when `Microsoft SwiftKey` is installed and enabled, it will actually [get the autocorrect settings](https://www.technipages.com/swiftkey-how-to-enable-or-disable-autocorrect) from its own app. Also, it looks like the spell check for MS SwiftKey works in the other way - it will not underline misspelled works with red.

Should we update the user with this info?

I believe this is not a Simplenote related issue and closing this one.

**Closed as completed by pachlava** 2021-07-13 12:30 UTC
Labels: [Type] Bug

**Comment by thabotswana** [comment] 2021-07-20 11:16
Thank you for checking this! I replied to the user.

**Comment by CameronMilliken** [comment] 2022-06-24 15:10
Misspelled words that are underlined with red, no alternative words appear at the bottom. All I see are black rectangular boxes with nothing in them.
![Screenshot_20220623-204129](https://user-images.githubusercontent.com/36011531/175564382-eefec726-087b-472e-99db-aa34e04960f9.jpg)
![Screenshot_20220623-204023](https://user-images.githubusercontent.com/36011531/175564394-5c3fe863-11f5-468e-9e25-4d9d1cb6d5ec.jpg)

https://woothemes.zendesk.com/agent/tickets/5290697
