### ISSUE TITLE
Creating, then deleting a note in Android app leaves empty note in Windows app

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/simplenote-android#521] opened 2018-04-16 12:31 UTC
## Summary

From 1072546-zen:

>When create new note on android and then press back you got no new note, but on windows you see empty note in ur list

## What I expected

Deleted notes should not appear in other, synced apps.

## Steps to reproduce

>Create new note on android
>Delete note on n android
>Open win app and get this bug

## What happened instead

User reported the following:

>Using windows 8.1. using latest app from Google play 1.5.8. affected every new note that was created in mobile client and then deleted in android app. Then you get empty note on your windows.

**Comment by theck13** [comment] 2019-05-29 05:35
I cannot reproduce that behavior.  Feel free to reopen this issue if you can.  It appears this was fixed in https://github.com/Automattic/simplenote-android/pull/532, which was included in Simplenote 1.6.8 and after.

**Closed by theck13** 2019-05-29 05:35 UTC
Labels: bug
