### ISSUE TITLE
table markdown preview not working

### ISSUE THREAD

**Issue by MorgothSauron** [Automattic/simplenote-android#499] opened 2018-02-26 21:02 UTC
The following text is displayed as a table when in preview mode on Linux (1.1.3):
```
First Header  | Second Header|Third Header
------------- | -------------|----
Content Cell  | Content Cell| Content Cell
Content Cell  | Content Cell | Content Cell
New Row|New Row|New Row
```
![linux_table](https://user-images.githubusercontent.com/6804228/36694873-eb0f0f8e-1b3f-11e8-966c-25662adecb7b.png)

However, it does not work on Android
![android_table](https://user-images.githubusercontent.com/6804228/36695099-8e6fe036-1b40-11e8-9a43-894aa228f97b.png)

If it's supported on Android, why is doesn't work ?
If not supported, any plan to add the feature

**Comment by merit2018** [comment] 2018-09-08 10:02
I have the same problem in Win10 and android. It shows up fine on my screen, but the published version that people see in all browsers is as MorgothSauron states

**Comment by PhiLhoSoft** [comment] 2018-09-14 08:55
Seems to be a duplicate of #392.
But basically I agree, this is really missing!

**Comment by roundhill** [comment] 2018-09-25 22:48
What Android devices are y'all using?

**Comment by PhiLhoSoft** [comment] 2018-09-26 21:11
I see the problem on an old Samsung Galaxy Tab E (Android 4.4.4) and on an Honor 9 phone (Android 8.0.0). Using Simplenote 1.6.5 on both.

**Comment by theck13** [comment] 2019-05-27 15:39
I cannot reproduce that behavior.  Feel free to reopen this issue if you can.  I copied the content below from the original comment and the table rendered as expected.

```
First Header  | Second Header|Third Header
------------- | -------------|----
Content Cell  | Content Cell| Content Cell
Content Cell  | Content Cell | Content Cell
New Row|New Row|New Row
```

See the screenshots below for illustration.

![499](https://user-images.githubusercontent.com/3827611/58429458-33c24c80-8063-11e9-86d6-fcef777ef549.png)

**Closed by theck13** 2019-05-27 15:39 UTC

**Comment by PhiLhoSoft** [comment] 2019-05-28 08:32
OK, I made more tests, and in my case, it was, at least partially, my fault.
I had the following table (shortened):

```
âge | classe | G (cm) | (IMC) | F (cm) | (IMC)
--|--|--|--|--|--
6 ans | CP | 105-128 | 13.5-18.0 | 105-125 | 13.0-17.7
7 ans | CE1 | 112-132 | 13.4-18.2 | 110-132 | 13.0-18.0
```
âge | classe | G (cm) | (IMC) | F (cm) | (IMC)
--|--|--|--|--|--
6 ans | CP | 105-128 | 13.5-18.0 | 105-125 | 13.0-17.7
7 ans | CE1 | 112-132 | 13.4-18.2 | 110-132 | 13.0-18.0

Funnily, GitHub and Simplenote for Windows render it correctly.
I checked a [quick reference](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) which states _There must be at least 3 dashes separating each header cell._ Woops.
And indeed, once I have put `---|---|---|---|---|---` in the second line, it displayed correctly in the Android version (1.7 now).

Perhaps the Android version can be made more permissive, to align on the desktop version, as it is a source of confusion, but currently, the issue is rightfully closed. 😄
