### ISSUE TITLE
App crash while signing in with WordPress.com

### ISSUE THREAD

**Issue by hypest** [Automattic/simplenote-android#681] opened 2019-05-22 21:07 UTC
### Expected
I would expect to be able to log in with WordPress.com.

### Observed
App crashes as soon as I tap on the "Sign in with WordPress.com" button.

Here's a gif of the crash on my phone:

![2019_05_23_00_01_00_trim 2019-05-23 00_04_32](https://user-images.githubusercontent.com/1032913/58208856-5c0e1c00-7cee-11e9-9d5a-251e169f1c00.gif)

### Reproduced
1. Install v1.7.0 of the app from the Play store
2. Launch the app
3. Tap on the "Sign in with WordPress.com" textual button
4. 💥 

Make|Model|Android Version|App Version
-|-|-|-
Samsung|Galaxy s7Edge (SM-G935F)|8.0.0|1.7.0

Crashlog from logcat:

```
2019-05-24 11:22:02.178 16801-16801/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.automattic.simplenote, PID: 16801
    android.content.ActivityNotFoundException
        at net.openid.appauth.AuthorizationService.prepareAuthorizationRequestIntent(Unknown Source:9)
        at net.openid.appauth.AuthorizationService.getAuthorizationRequestIntent(Unknown Source:0)
        at net.openid.appauth.AuthorizationService.getAuthorizationRequestIntent(Unknown Source:11)
        at com.automattic.simplenote.SignInActivity$1.onClick(Unknown Source:50)
        at android.view.View.performClick(View.java:6897)
        at android.view.View$PerformClick.run(View.java:26101)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by theck13** [comment] 2019-06-06 15:19
We've tried reproducing this issue on two different Samsung Galaxy S6 devices, but we were unable to see the crash.  Is there any unique configuration on that device?  Specifically, is there at least one browser app?  If so, are there any unique settings for the default browser?  The _*Sign In with WordPress.com*_ button sends the user to the browser app for authentication.  That appears to be where the crash is occurring on your device.

**Comment by hypest** [comment] 2019-06-07 07:53
The default browser on my S7 is Opera. I changed it to Chrome (verified it by opening a URL from elsewhere too) but the issue is still happening 😢

**Comment by theck13** [comment] 2019-10-16 18:54
@hypest, login/signup has changed since this issue was created.  Can you update to Simplenote 2.0.0 and try to reproduce the crash again?  I tested a Samsung Galaxy S6 (SM-G920I) running Android 7.0 with Simplenote 2.0.0 and I want able to reproduce the crash.

**Comment by hypest** [comment] 2019-10-17 08:31
Same error with v2.0.0 (same device and OS version as before, S7Edge Android 8.0.0), though with a different codepath in the stacktrace:

```
2019-10-17 11:29:50.661 10954-10954/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.automattic.simplenote, PID: 10954
    android.content.ActivityNotFoundException
        at net.openid.appauth.AuthorizationService.prepareAuthorizationRequestIntent(Unknown Source:88)
        at net.openid.appauth.AuthorizationService.getAuthorizationRequestIntent(Unknown Source:0)
        at net.openid.appauth.AuthorizationService.getAuthorizationRequestIntent(Unknown Source:11)
        at com.automattic.simplenote.SimplenoteAuthenticationActivity.onLoginSheetOtherClicked(Unknown Source:41)
        at com.simperium.android.LoginBottomSheetDialogFragment$2.onClick(Unknown Source:6)
        at android.view.View.performClick(View.java:6897)
        at android.widget.TextView.performClick(TextView.java:12693)
        at android.view.View$PerformClick.run(View.java:26101)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by theck13** [comment] 2019-10-17 17:00
Thanks for checking and the updated stack trace, @hypest!  Looking at our crash reporting, there are only two users that have experience this including you.  Since I can't reproduce it and it appears to be a very low number of events, I'll close this issue for now.  If we get more reports of this crash, I'll reopen it.

**Closed by theck13** 2019-10-17 17:00 UTC
Labels: bug, crash
